In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('data/GameSales.csv')
df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.columns

Index(['Name', 'Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales', 'Critic_Score',
       'Critic_Count', 'User_Score', 'User_Count', 'Developer', 'Rating'],
      dtype='object')

In [6]:
df['Genre'].unique()

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy', nan], dtype=object)

In [7]:
df[df['Genre'].isna()]

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
659,NaN,GEN,1993.0,NaN,Acclaim Entertainment,1.78,0.53,0.00,0.08,2.39,NaN,NaN,NaN,NaN,NaN,NaN
14246,NaN,GEN,1993.0,NaN,Acclaim Entertainment,0.00,0.00,0.03,0.00,0.03,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df = df.dropna(subset=['Genre'])

In [9]:
df['Platform'].unique()

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       'PS4', '3DS', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne',
       'WiiU', 'GC', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16',
       '3DO', 'GG', 'PCFX'], dtype=object)

In [10]:
console_brand = {'Nintendo' : ['Wii','WiiU', 'NES',
                              'GB', 'GBA', 'DS', 'SNES', '3DS', 'N64', 'GC', '3DO'],
                              'Microsoft' : ['X360', 'XB', 'Xone'],
                              'Sony' : ['PS3', 'PS2', 'PS4', 'PS', 'PSP', 'PSV']}

In [11]:
lst = []
for each in df['Platform']:
    flag = 0
    for key, value in console_brand.items():
        if each in value:
            lst.append(key)
            flag = 1
    if not flag:
        lst.append(np.NAN)
df['Plat_Brand'] = lst

In [12]:
df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Plat_Brand
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E,Nintendo
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN,Nintendo
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,Nintendo
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E,Nintendo
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN,Nintendo

In [13]:
df.to_csv('data/GameSales_cleaned.csv')

In [14]:
import dash
from dash.dependencies import Input, Output, State
from dash import dcc
from dash import html

In [21]:
df['Year_of_Release'].max()

2020.0

In [27]:
df[df['Platform'] == 'PC']

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Plat_Brand
85,The Sims 3,PC,2009.0,Simulation,Electronic Arts,0.99,6.42,0.0,0.60,8.01,86.0,75.0,7.6,886.0,The Sims Studio,T,NaN
138,World of Warcraft,PC,2004.0,Role-Playing,Activision,0.08,6.21,0.0,0.00,6.29,93.0,57.0,7.3,2182.0,Blizzard Entertainment,T,NaN
192,Diablo III,PC,2012.0,Role-Playing,Activision,2.44,2.16,0.0,0.54,5.14,88.0,86.0,4.0,9629.0,Blizzard Entertainment,M,NaN
195,Microsoft Flight Simulator,PC,1996.0,Simulation,Microsoft Game Studios,3.22,1.69,0.0,0.20,5.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,StarCraft II: Wings of Liberty,PC,2010.0,Strategy,Activision,2.57,1.68,0.0,0.58,4.84,93.0,82.0,8.2,3052.0,Blizzard Entertainment,T,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16694,Pony Friends 2,PC,2009.0,Simulation,Eidos Interactive,0.00,0.01,0.0,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16696,Metal Gear Solid V: Ground Zeroes,PC,2014.0,Action,Konami Digital Entertainment,0.00,0.01,0.0,0.00,0.01,80.0,20.0,7.6,412.0,Kojima Productions,M,NaN
16700,Breach,PC,2011.0,Shooter,Destineer,0.01,0.00,0.0,0.00,0.01,61.0,12.0,5.8,43.0,Atomic Games,T,NaN
16706,STORM: Frontline Nation,PC,2011.0,Strategy,Unknown,0.00,0.01,0.0,0.00,0.01,60.0,12.0,7.2,13.0,SimBin,E10+,NaN
16709,15 Days,PC,2009.0,Adventure,DTP Entertainment,0.00,0.01,0.0,0.00,0.01,63.0,6.0,5.8,8.0,DTP Entertainment,NaN,NaN